#pragma once

#include "Ark/System/Key.hpp"
#include "Ark/System/Scancode.hpp"

namespace Ark::Platform::MacOS
{
    inline Scancode mapKeyCodeToScancode(unsigned short keyCode)
    {
        switch (keyCode)
        {
            case 0:
                return Scancode::A;
            case 1:
                return Scancode::S;
            case 2:
                return Scancode::D;
            case 3:
                return Scancode::F;
            case 4:
                return Scancode::H;
            case 5:
                return Scancode::G;
            case 6:
                return Scancode::Z;
            case 7:
                return Scancode::X;
            case 8:
                return Scancode::C;
            case 9:
                return Scancode::V;
            case 11:
                return Scancode::B;
            case 12:
                return Scancode::Q;
            case 13:
                return Scancode::W;
            case 14:
                return Scancode::E;
            case 15:
                return Scancode::R;
            case 16:
                return Scancode::Y;
            case 17:
                return Scancode::T;
            case 18:
                return Scancode::Digit1;
            case 19:
                return Scancode::Digit2;
            case 20:
                return Scancode::Digit3;
            case 21:
                return Scancode::Digit4;
            case 22:
                return Scancode::Digit6;
            case 23:
                return Scancode::Digit5;
            case 24:
                return Scancode::Equals;
            case 25:
                return Scancode::Digit9;
            case 26:
                return Scancode::Digit7;
            case 27:
                return Scancode::Minus;
            case 28:
                return Scancode::Digit8;
            case 29:
                return Scancode::Digit0;
            case 30:
                return Scancode::RightBracket;
            case 31:
                return Scancode::O;
            case 32:
                return Scancode::U;
            case 33:
                return Scancode::LeftBracket;
            case 34:
                return Scancode::I;
            case 35:
                return Scancode::P;
            case 36:
                return Scancode::Return;
            case 37:
                return Scancode::L;
            case 38:
                return Scancode::J;
            case 39:
                return Scancode::Apostrophe;
            case 40:
                return Scancode::K;
            case 41:
                return Scancode::Semicolon;
            case 42:
                return Scancode::Backslash;
            case 43:
                return Scancode::Comma;
            case 44:
                return Scancode::Slash;
            case 45:
                return Scancode::N;
            case 46:
                return Scancode::M;
            case 47:
                return Scancode::Period;
            case 48:
                return Scancode::Tab;
            case 49:
                return Scancode::Space;
            case 50:
                return Scancode::GraveAccent;
            case 51:
                return Scancode::Backspace;
            case 53:
                return Scancode::Escape;
            case 54:
                return Scancode::RightCmd;
            case 55:
                return Scancode::LeftCmd;
            case 56:
                return Scancode::LeftShift;
            case 57:
                return Scancode::CapsLock;
            case 58:
                return Scancode::LeftAlt;
            case 59:
                return Scancode::LeftControl;
            case 60:
                return Scancode::RightShift;
            case 61:
                return Scancode::RightAlt;
            case 62:
                return Scancode::RightControl;
            case 64:
                return Scancode::F17;
            case 65:
                return Scancode::KeypadPeriod;
            case 67:
                return Scancode::KeypadMultiply;
            case 69:
                return Scancode::KeypadPlus;
            case 71:
                return Scancode::NumLockClear;
            case 75:
                return Scancode::KeypadDivide;
            case 76:
                return Scancode::KeypadEnter;
            case 78:
                return Scancode::KeypadMinus;
            case 79:
                return Scancode::F18;
            case 80:
                return Scancode::F19;
            case 81:
                return Scancode::KeypadEquals;
            case 82:
                return Scancode::Keypad0;
            case 83:
                return Scancode::Keypad1;
            case 84:
                return Scancode::Keypad2;
            case 85:
                return Scancode::Keypad3;
            case 86:
                return Scancode::Keypad4;
            case 87:
                return Scancode::Keypad5;
            case 88:
                return Scancode::Keypad6;
            case 89:
                return Scancode::Keypad7;
            case 90:
                return Scancode::F20;
            case 91:
                return Scancode::Keypad8;
            case 92:
                return Scancode::Keypad9;
            case 96:
                return Scancode::F5;
            case 97:
                return Scancode::F6;
            case 98:
                return Scancode::F7;
            case 99:
                return Scancode::F3;
            case 100:
                return Scancode::F8;
            case 101:
                return Scancode::F9;
            case 103:
                return Scancode::F11;
            case 105:
                return Scancode::F13;
            case 106:
                return Scancode::F16;
            case 107:
                return Scancode::F14;
            case 109:
                return Scancode::F10;
            case 111:
                return Scancode::F12;
            case 113:
                return Scancode::F15;
            case 114:
                return Scancode::Help;
            case 115:
                return Scancode::Home;
            case 116:
                return Scancode::PageUp;
            case 117:
                return Scancode::Delete;
            case 118:
                return Scancode::F4;
            case 119:
                return Scancode::End;
            case 120:
                return Scancode::F2;
            case 121:
                return Scancode::PageDown;
            case 122:
                return Scancode::F1;
            case 123:
                return Scancode::Left;
            case 124:
                return Scancode::Right;
            case 125:
                return Scancode::Down;
            case 126:
                return Scancode::Up;
            default:
                return Scancode::Unknown;
        }
    }

    inline Key scancodeToKey(Scancode scancode)
    {
        switch (scancode)
        {
            case Scancode::A:
                return Key::A;
            case Scancode::B:
                return Key::B;
            case Scancode::C:
                return Key::C;
            case Scancode::D:
                return Key::D;
            case Scancode::E:
                return Key::E;
            case Scancode::F:
                return Key::F;
            case Scancode::G:
                return Key::G;
            case Scancode::H:
                return Key::H;
            case Scancode::I:
                return Key::I;
            case Scancode::J:
                return Key::J;
            case Scancode::K:
                return Key::K;
            case Scancode::L:
                return Key::L;
            case Scancode::M:
                return Key::M;
            case Scancode::N:
                return Key::N;
            case Scancode::O:
                return Key::O;
            case Scancode::P:
                return Key::P;
            case Scancode::Q:
                return Key::Q;
            case Scancode::R:
                return Key::R;
            case Scancode::S:
                return Key::S;
            case Scancode::T:
                return Key::T;
            case Scancode::U:
                return Key::U;
            case Scancode::V:
                return Key::V;
            case Scancode::W:
                return Key::W;
            case Scancode::X:
                return Key::X;
            case Scancode::Y:
                return Key::Y;
            case Scancode::Z:
                return Key::Z;
            case Scancode::Digit0:
                return Key::Digit0;
            case Scancode::Digit1:
                return Key::Digit1;
            case Scancode::Digit2:
                return Key::Digit2;
            case Scancode::Digit3:
                return Key::Digit3;
            case Scancode::Digit4:
                return Key::Digit4;
            case Scancode::Digit5:
                return Key::Digit5;
            case Scancode::Digit6:
                return Key::Digit6;
            case Scancode::Digit7:
                return Key::Digit7;
            case Scancode::Digit8:
                return Key::Digit8;
            case Scancode::Digit9:
                return Key::Digit9;
            case Scancode::Return:
                return Key::Return;
            case Scancode::Escape:
                return Key::Escape;
            case Scancode::Backspace:
                return Key::Backspace;
            case Scancode::Tab:
                return Key::Tab;
            case Scancode::Space:
                return Key::Space;
            case Scancode::Minus:
                return Key::Minus;
            case Scancode::Equals:
                return Key::Equals;
            case Scancode::LeftBracket:
                return Key::LeftBracket;
            case Scancode::RightBracket:
                return Key::RightBracket;
            case Scancode::Backslash:
                return Key::Backslash;
            case Scancode::Semicolon:
                return Key::Semicolon;
            case Scancode::Apostrophe:
                return Key::Apostrophe;
            case Scancode::GraveAccent:
                return Key::GraveAccent;
            case Scancode::Comma:
                return Key::Comma;
            case Scancode::Period:
                return Key::Period;
            case Scancode::Slash:
                return Key::Slash;
            case Scancode::CapsLock:
                return Key::CapsLock;
            case Scancode::F1:
                return Key::F1;
            case Scancode::F2:
                return Key::F2;
            case Scancode::F3:
                return Key::F3;
            case Scancode::F4:
                return Key::F4;
            case Scancode::F5:
                return Key::F5;
            case Scancode::F6:
                return Key::F6;
            case Scancode::F7:
                return Key::F7;
            case Scancode::F8:
                return Key::F8;
            case Scancode::F9:
                return Key::F9;
            case Scancode::F10:
                return Key::F10;
            case Scancode::F11:
                return Key::F11;
            case Scancode::F12:
                return Key::F12;
            case Scancode::PrintScreen:
                return Key::PrintScreen;
            case Scancode::ScrollLock:
                return Key::ScrollLock;
            case Scancode::Pause:
                return Key::Pause;
            case Scancode::Insert:
                return Key::Insert;
            case Scancode::Home:
                return Key::Home;
            case Scancode::PageUp:
                return Key::PageUp;
            case Scancode::Delete:
                return Key::Delete;
            case Scancode::End:
                return Key::End;
            case Scancode::PageDown:
                return Key::PageDown;
            case Scancode::Right:
                return Key::Right;
            case Scancode::Left:
                return Key::Left;
            case Scancode::Down:
                return Key::Down;
            case Scancode::Up:
                return Key::Up;
            case Scancode::NumLockClear:
                return Key::NumLockClear;
            case Scancode::KeypadDivide:
                return Key::KeypadDivide;
            case Scancode::KeypadMultiply:
                return Key::KeypadMultiply;
            case Scancode::KeypadMinus:
                return Key::KeypadMinus;
            case Scancode::KeypadPlus:
                return Key::KeypadPlus;
            case Scancode::KeypadEnter:
                return Key::KeypadEnter;
            case Scancode::Keypad1:
                return Key::Keypad1;
            case Scancode::Keypad2:
                return Key::Keypad2;
            case Scancode::Keypad3:
                return Key::Keypad3;
            case Scancode::Keypad4:
                return Key::Keypad4;
            case Scancode::Keypad5:
                return Key::Keypad5;
            case Scancode::Keypad6:
                return Key::Keypad6;
            case Scancode::Keypad7:
                return Key::Keypad7;
            case Scancode::Keypad8:
                return Key::Keypad8;
            case Scancode::Keypad9:
                return Key::Keypad9;
            case Scancode::Keypad0:
                return Key::Keypad0;
            case Scancode::KeypadPeriod:
                return Key::KeypadPeriod;
            case Scancode::KeypadEquals:
                return Key::KeypadEquals;
            case Scancode::F13:
                return Key::F13;
            case Scancode::F14:
                return Key::F14;
            case Scancode::F15:
                return Key::F15;
            case Scancode::F16:
                return Key::F16;
            case Scancode::F17:
                return Key::F17;
            case Scancode::F18:
                return Key::F18;
            case Scancode::F19:
                return Key::F19;
            case Scancode::F20:
                return Key::F20;
            case Scancode::Help:
                return Key::Help;
            case Scancode::LeftControl:
                return Key::LeftControl;
            case Scancode::LeftShift:
                return Key::LeftShift;
            case Scancode::LeftAlt:
                return Key::LeftAlt;
            case Scancode::LeftCmd:
                return Key::LeftCmd;
            case Scancode::RightControl:
                return Key::RightControl;
            case Scancode::RightShift:
                return Key::RightShift;
            case Scancode::RightAlt:
                return Key::RightAlt;
            case Scancode::RightCmd:
                return Key::RightCmd;
            default:
                return Key::Unknown;
        }
    }
}
