#pragma once

#include "Ark/System/Key.hpp"
#include "Ark/System/Scancode.hpp"

namespace Ark::Platform::Windows
{
    inline Key mapVirtualKeyToKey(unsigned int vk)
    {
        switch (vk)
        {
            case 0x08:
                return Key::Backspace;
            case 0x09:
                return Key::Tab;
            case 0x0C:
                return Key::Clear;
            case 0x0D:
                return Key::Return;
            case 0x10:
                return Key::LeftShift;
            case 0x11:
                return Key::LeftControl;
            case 0x12:
                return Key::LeftAlt;
            case 0x13:
                return Key::Pause;
            case 0x14:
                return Key::CapsLock;
            case 0x1B:
                return Key::Escape;
            case 0x20:
                return Key::Space;
            case 0x21:
                return Key::PageUp;
            case 0x22:
                return Key::PageDown;
            case 0x23:
                return Key::End;
            case 0x24:
                return Key::Home;
            case 0x25:
                return Key::Left;
            case 0x26:
                return Key::Up;
            case 0x27:
                return Key::Right;
            case 0x28:
                return Key::Down;
            case 0x2C:
                return Key::PrintScreen;
            case 0x2D:
                return Key::Insert;
            case 0x2E:
                return Key::Delete;
            case 0x30:
                return Key::Digit0;
            case 0x31:
                return Key::Digit1;
            case 0x32:
                return Key::Digit2;
            case 0x33:
                return Key::Digit3;
            case 0x34:
                return Key::Digit4;
            case 0x35:
                return Key::Digit5;
            case 0x36:
                return Key::Digit6;
            case 0x37:
                return Key::Digit7;
            case 0x38:
                return Key::Digit8;
            case 0x39:
                return Key::Digit9;
            case 0x41:
                return Key::A;
            case 0x42:
                return Key::B;
            case 0x43:
                return Key::C;
            case 0x44:
                return Key::D;
            case 0x45:
                return Key::E;
            case 0x46:
                return Key::F;
            case 0x47:
                return Key::G;
            case 0x48:
                return Key::H;
            case 0x49:
                return Key::I;
            case 0x4A:
                return Key::J;
            case 0x4B:
                return Key::K;
            case 0x4C:
                return Key::L;
            case 0x4D:
                return Key::M;
            case 0x4E:
                return Key::N;
            case 0x4F:
                return Key::O;
            case 0x50:
                return Key::P;
            case 0x51:
                return Key::Q;
            case 0x52:
                return Key::R;
            case 0x53:
                return Key::S;
            case 0x54:
                return Key::T;
            case 0x55:
                return Key::U;
            case 0x56:
                return Key::V;
            case 0x57:
                return Key::W;
            case 0x58:
                return Key::X;
            case 0x59:
                return Key::Y;
            case 0x5A:
                return Key::Z;
            case 0x5B:
                return Key::LeftCmd;
            case 0x5C:
                return Key::RightCmd;
            case 0x5D:
                return Key::Application;
            case 0x60:
                return Key::Keypad0;
            case 0x61:
                return Key::Keypad1;
            case 0x62:
                return Key::Keypad2;
            case 0x63:
                return Key::Keypad3;
            case 0x64:
                return Key::Keypad4;
            case 0x65:
                return Key::Keypad5;
            case 0x66:
                return Key::Keypad6;
            case 0x67:
                return Key::Keypad7;
            case 0x68:
                return Key::Keypad8;
            case 0x69:
                return Key::Keypad9;
            case 0x6A:
                return Key::KeypadMultiply;
            case 0x6B:
                return Key::KeypadPlus;
            case 0x6D:
                return Key::KeypadMinus;
            case 0x6E:
                return Key::KeypadPeriod;
            case 0x6F:
                return Key::KeypadDivide;
            case 0x70:
                return Key::F1;
            case 0x71:
                return Key::F2;
            case 0x72:
                return Key::F3;
            case 0x73:
                return Key::F4;
            case 0x74:
                return Key::F5;
            case 0x75:
                return Key::F6;
            case 0x76:
                return Key::F7;
            case 0x77:
                return Key::F8;
            case 0x78:
                return Key::F9;
            case 0x79:
                return Key::F10;
            case 0x7A:
                return Key::F11;
            case 0x7B:
                return Key::F12;
            case 0x7C:
                return Key::F13;
            case 0x7D:
                return Key::F14;
            case 0x7E:
                return Key::F15;
            case 0x7F:
                return Key::F16;
            case 0x80:
                return Key::F17;
            case 0x81:
                return Key::F18;
            case 0x82:
                return Key::F19;
            case 0x83:
                return Key::F20;
            case 0x84:
                return Key::F21;
            case 0x85:
                return Key::F22;
            case 0x86:
                return Key::F23;
            case 0x87:
                return Key::F24;
            case 0x90:
                return Key::NumLockClear;
            case 0x91:
                return Key::ScrollLock;
            case 0xA0:
                return Key::LeftShift;
            case 0xA1:
                return Key::RightShift;
            case 0xA2:
                return Key::LeftControl;
            case 0xA3:
                return Key::RightControl;
            case 0xA4:
                return Key::LeftAlt;
            case 0xA5:
                return Key::RightAlt;
            case 0xAD:
                return Key::Mute;
            case 0xAE:
                return Key::VolumeDown;
            case 0xAF:
                return Key::VolumeUp;
            case 0xB0:
                return Key::MediaNextTrack;
            case 0xB1:
                return Key::MediaPreviousTrack;
            case 0xB2:
                return Key::MediaStop;
            case 0xB3:
                return Key::MediaPlayPause;
            case 0xBA:
                return Key::Semicolon;
            case 0xBB:
                return Key::Equals;
            case 0xBC:
                return Key::Comma;
            case 0xBD:
                return Key::Minus;
            case 0xBE:
                return Key::Period;
            case 0xBF:
                return Key::Slash;
            case 0xC0:
                return Key::GraveAccent;
            case 0xDB:
                return Key::LeftBracket;
            case 0xDC:
                return Key::Backslash;
            case 0xDD:
                return Key::RightBracket;
            case 0xDE:
                return Key::Apostrophe;
            default:
                return Key::Unknown;
        }
    }
}
