#pragma once

#include "Ark/Core/Flags.hpp"
#include "Ark/Core/Macros.hpp"
#include "Ark/Core/Types.hpp"

namespace Ark
{
    /// Logical keyboard key identifiers.
    /// Values represent semantic keys independent of physical keyboard layout.
    enum class Key : uint32
    {
        Unknown,

        Return,
        Escape,
        Backspace,
        Tab,
        Space,

        Exclaim,
        DoubleApostrophe,
        Hash,
        Dollar,
        Percent,
        Ampersand,
        Apostrophe,
        LeftParen,
        RightParen,
        Asterisk,
        Plus,
        Comma,
        Minus,
        Period,
        Slash,

        Digit0,
        Digit1,
        Digit2,
        Digit3,
        Digit4,
        Digit5,
        Digit6,
        Digit7,
        Digit8,
        Digit9,

        Colon,
        Semicolon,
        Less,
        Equals,
        Greater,
        Question,
        At,

        LeftBracket,
        Backslash,
        RightBracket,
        Caret,
        Underscore,
        GraveAccent,

        A,
        B,
        C,
        D,
        E,
        F,
        G,
        H,
        I,
        J,
        K,
        L,
        M,
        N,
        O,
        P,
        Q,
        R,
        S,
        T,
        U,
        V,
        W,
        X,
        Y,
        Z,

        LeftBrace,
        Pipe,
        RightBrace,
        Tilde,
        Delete,

        PlusOrMinus,

        CapsLock,
        F1,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        F10,
        F11,
        F12,
        PrintScreen,
        ScrollLock,
        Pause,
        Insert,
        Home,
        PageUp,
        End,
        PageDown,
        Right,
        Left,
        Down,
        Up,

        NumLockClear,
        KeypadDivide,
        KeypadMultiply,
        KeypadMinus,
        KeypadPlus,
        KeypadEnter,
        Keypad1,
        Keypad2,
        Keypad3,
        Keypad4,
        Keypad5,
        Keypad6,
        Keypad7,
        Keypad8,
        Keypad9,
        Keypad0,
        KeypadPeriod,

        Application,
        Power,
        KeypadEquals,
        F13,
        F14,
        F15,
        F16,
        F17,
        F18,
        F19,
        F20,
        F21,
        F22,
        F23,
        F24,
        Execute,
        Help,
        Menu,
        Select,
        Stop,
        Again,
        Undo,
        Cut,
        Copy,
        Paste,
        Find,
        Mute,
        VolumeUp,
        VolumeDown,
        KeypadComma,
        KeypadEqualsAS400,

        AltErase,
        SystemRequest,
        Cancel,
        Clear,
        Prior,
        Return2,
        Separator,
        Out,
        Oper,
        ClearAgain,
        CursorSelect,
        ExtendSelect,

        Keypad00,
        Keypad000,
        ThousandsSeparator,
        DecimalSeparator,
        CurrencyUnit,
        CurrencySubunit,
        KeypadLeftParen,
        KeypadRightParen,
        KeypadLeftBrace,
        KeypadRightBrace,
        KeypadTab,
        KeypadBackspace,
        KeypadA,
        KeypadB,
        KeypadC,
        KeypadD,
        KeypadE,
        KeypadF,
        KeypadXor,
        KeypadPower,
        KeypadPercent,
        KeypadLess,
        KeypadGreater,
        KeypadAmpersand,
        KeypadDoubleAmpersand,
        KeypadVerticalBar,
        KeypadDoubleVerticalBar,
        KeypadColon,
        KeypadHash,
        KeypadSpace,
        KeypadAt,
        KeypadExclam,
        KeypadMemStore,
        KeypadMemRecall,
        KeypadMemClear,
        KeypadMemAdd,
        KeypadMemSubtract,
        KeypadMemMultiply,
        KeypadMemDivide,
        KeypadPlusOrMinus,
        KeypadClear,
        KeypadClearEntry,
        KeypadBinary,
        KeypadOctal,
        KeypadDecimal,
        KeypadHexadecimal,

        LeftControl,
        LeftShift,
        LeftAlt,
        LeftCmd,
        RightControl,
        RightShift,
        RightAlt,
        RightCmd,

        ModeSwitch,
        Sleep,
        Wake,
        ChannelIncrement,
        ChannelDecrement,
        MediaPlay,
        MediaPause,
        MediaRecord,
        MediaFastForward,
        MediaRewind,
        MediaNextTrack,
        MediaPreviousTrack,
        MediaStop,
        MediaEject,
        MediaPlayPause,
        MediaSelect,

        ApplicationControlNew,
        ApplicationControlOpen,
        ApplicationControlClose,
        ApplicationControlExit,
        ApplicationControlSave,
        ApplicationControlPrint,
        ApplicationControlProperties,
        ApplicationControlSearch,
        ApplicationControlHome,
        ApplicationControlBack,
        ApplicationControlForward,
        ApplicationControlStop,
        ApplicationControlRefresh,
        ApplicationControlBookmarks,

        SoftLeft,
        SoftRight,
        Call,
        EndCall,

        LeftTab,
        Level5Shift,
        MultiKeyCompose,
        LeftMeta,
        RightMeta,
        LeftHyper,
        RightHyper,
    };

    enum class KeyModifiers : uint16
    {
        None = 0,

        LeftShift = ARK_BIT(0),
        RightShift = ARK_BIT(1),
        Level5 = ARK_BIT(2),
        LeftControl = ARK_BIT(6),
        RightControl = ARK_BIT(7),
        LeftAlt = ARK_BIT(8),
        RightAlt = ARK_BIT(9),
        LeftCmd = ARK_BIT(10),
        RightCmd = ARK_BIT(11),
        Num = ARK_BIT(12),
        Caps = ARK_BIT(13),
        Mode = ARK_BIT(14),
        Scroll = ARK_BIT(15),

        Control = LeftControl | RightControl,
        Shift = LeftShift | RightShift,
        Alt = LeftAlt | RightAlt,
        Cmd = LeftCmd | RightCmd,
    };

    ARK_FLAG_ENUM(KeyModifiers)
}
